name: build
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Starting build
        run: echo "Hello World!"
      - name: Build in process
        run: echo "Build in progress"
      - name: Build success
        run: echo "Build successful"
