name: build
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: SLack Notification on success
        uses: act10ns/slack@v1
        with:
          status: ${{job.status}}
          steps: ${{toJson(steps)}}
          channel: #testing-github-actions
        if: always()
